SELECT "VERSAO".NOME, "LIVRO".NOME, "VERSICULO".CAPITULO, "VERSICULO".VERSICULO, "VERSICULO".TEXTO
FROM "VERSICULO"
JOIN "VERSAO" 
ON "VERSAO".ID = "VERSICULO".ID_VERSAO
JOIN "LIVRO" 
ON "VERSICULO".LIVRO_ID = "LIVRO".ID
-- INCOMPLETO FAVOR CONTINUAR
